name: pins-on-the-map
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - django
  - gdal
  - flake8
  - psycopg2
  - python-dotenv
  - black
  - gunicorn
  - whitenoise
  - djangorestframework
  - djangorestframework-gis
  - pip
