# Generated by Django 3.2.8 on 2021-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20211103_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapuser',
            name='q7',
            field=models.TextField(blank=True),
        ),
    ]
